theme: jekyll-theme-time-machine
gems:
  - jemoji
permalink: pretty
title: Ornament & Crime
description: A polymorphic CV generator module for eurorack modular synthesisers.
show_downloads: false
google_analytics:
